// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyhkuzpyfypzavtvsybf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aGt1enB5ZnlwemF2dHZzeWJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NTI5MzgsImV4cCI6MjA2ODMyODkzOH0.lJBvAUhqWF7ShovtCrerpdbb9CDVcrwZAkBFtp1bNfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});